### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by thehappycoder** [jay763190097/fill-pdf-utf8#4]
```
2018-11-06T02:40:13.210806600Z { Error: Command failed: java -jar "/app/node_modules/fill-pdf-utf8/lib/fill_pdf_utf8.jar" /app/cgu.pdf fontPath /app/node_modules/fill-pdf-utf8/lib/simfang.ttf fill_form - output - flatten </app/output/cgu.pdf-itext5.xfdf> /app/output/cgu.pdf-itext5.pdf
2018-11-06T02:40:13.210897100Z java.lang.NullPointerException
2018-11-06T02:40:13.210916800Z 	at com.stpass.fill_pdf_utf8.FillPdfForm.generatorFillForm(FillPdfForm.java:89)
2018-11-06T02:40:13.210953800Z 	at com.stpass.fill_pdf_utf8.FillPdfForm.execute(FillPdfForm.java:52)
2018-11-06T02:40:13.210974200Z 	at com.stpass.fill_pdf_utf8.FillPdfForm.xfdfFillPdf(FillPdfForm.java:35)
2018-11-06T02:40:13.210997200Z 	at com.stpass.fill_pdf_utf8.Main.main(Main.java:16)
```

```
fillPdf.generatePdf(
    { fields },
    '/app/cgu.pdf',
    'need_appearances',
    `/app/output/${path}-itext5.pdf`,
    (error: any, stdout: any, stderr: any) => {
      if (error) {
        console.error(error)
      } else {
        console.log('Yay!')
      }
    }
  )
```

**Comment by jay763190097** [comment]
sorry! I just responded to your message right now.  That's beacause I forgot to update readme.md this file.
I added a config to set font size.
